### ISSUE TITLE
Custom Controller Clone Overflow

### ISSUE THREAD

**Issue by ndumais** [FredMarquer/PortalFramework#1]
Hey, first of all, really cool repo, I've experimented with a few of them and this one already being tested with bhop/surf stuff is a big plus for me

**For some reason, when I try using a different controller, clones get generated till there's an overflow on game start**

I tried implementing the movement from this which is pretty much the best source engine kind of movement thing for unity
https://github.com/Fragsurf/Fragsurf-2

Repro steps
1. Took all the scripts from the Movement in https://github.com/Fragsurf/Fragsurf-2 and moved it to your project.
2. Commented code that was referencing missing stuff (not needed since they are mostly triggers)
3. Add the SurfCharacter to a random empty gameobject
4. Add a camera as a child and set parent & child Layer to Player

From that point you have a working SurfCharacter within the project
I then set it up just like your prefab in the test scene but only using the teleportable script on the player and the script on the camera too for portal rendering
and I add this code to the SurfCharacter (which might need a few more tweaks to work)

        void ITeleportCallback.OnTeleport(Portal portal, float newScale) {
            // this.scale = newScale;

            // Transform the velocity through the portal
            MoveData.Velocity = portal.DirectionThroughPortal(MoveData.Velocity);

            // Transform the ground normal through the portal
            MoveData.GroundNormal= portal.DirectionThroughPortal(MoveData.GroundNormal);
        }

**Comment by FredMarquer** [comment]
Hey, I'm glad to see someone using this project ^^

My first intuition is that you have a TeleportableObject component on your clone prefab (you should not use the same prefabs for the "original" object and the clone).

**Comment by ndumais** [comment]
Appreciate the fast reply, yeah that was exactly it
Had to do another fix to make the teleportation work but doesn't seem like that's the right way to do it, cause it will teleport the player up aswell (cause i assume transform.position is the center of the portal's volume)
```
        void ITeleportCallback.OnTeleport(Portal portal, float newScale) {
            ...
            MoveData.Origin = portal.DestinationPortal.transform.position;
        }
```

How would you do it?

I think I might just need to understand how the TransformThroughPortal method works OR take the position right after it completes and give it to MoveData.Origin

A dirty way to do it probably to modify TransformThroughPortal to return the Transform, and then use that in my controller, but it's probably getting called twice then (but doesn't seem like it's too big of a deaL)

no luck so far though

**Comment by FredMarquer** [comment]
You need to call PositionThroughPortal with `MoveData.Origin` as paramter:
```
MoveData.Origin = portal.PositionThroughPortal(MoveData.Origin);
```

You will also need to apply a transformation to the rotation of your charater `MoveData.ViewAngles`:
```
Quaternion rotation = Quaternion.Euler(MoveData.ViewAngles);
rotation = portal.RotationThroughPortal(rotation);
MoveData.ViewAngles = rotation.eulerAngles;
```

Also, looking at the MoveData struct, there may be other fields that would need to be transformed through the portal (the Vector3  fields).
