### ISSUE TITLE
[WebGL] Portals Not Working with HDR

### ISSUE THREAD

**Issue by ndumais** [FredMarquer/PortalFramework#2]
Hey, almost fully resolved the other issue, has a small thing left I thought I'd make a build to show but realized the shader looks super distorted in WebGL for some reason, still reading to try to figure out what's happening

It's almost as if the further away you are the more zoomed in it is, and it will only look normal when you right next to the portal, thought I'd at least document it here for now

(here you can see how zoomed in it looks from far away)
![image](https://github.com/user-attachments/assets/0bbeca84-2c15-450e-9180-d2550eb28fdf)

(here you can see how from up close it looks almost normal, but things are off, and portals far away you can see the same issue as above)
![image](https://github.com/user-attachments/assets/c5a6dede-bfc2-4676-b4c4-4c15ef60ed2a)

**Comment by FredMarquer** [comment]
Hey, it looks like the camera projection matrix or viewport used to render the portals is messed up. I don't know what could cause this issue. I built and tried the project for WebGL on my side, but it works fine for me :/

What version of Unity are you using? Do you have other plugin or code that could impact the rendering in some way?
It could also be some kind of compatibility issue, WebGL can be annoying for this kind of stuff. Can you try to launch the build with different web browser? Or with a different computer (if you have another one at hand ^^)?

**Comment by ndumais** [comment]
Oh wow, so it works for you with WebGL in a browser outside the Editor?

And have you tried with a vanilla version of your project from GitHub?
I'm pretty sure I tried that but I'll have to try again if that's work for you

I've tried two different browsers without luck, you can try too if it worked for you?
https://offthetop.itch.io/surf > Play > portal_test4

**Comment by FredMarquer** [comment]
Hey, I tried your build and it didn't work on my computer :/

To make my build works I had to add the "Hidden/Portal" shader to the "Always included Shaders" list in Project Settings -> Graphics. Have you done that?

Also, did you you try to build your game for desktop to see if it works?

**Comment by ndumais** [comment]
Found out what it was thanks to your last message, turns out my camera was using default graphics settings, and portals don't work with HDR for some reason, renamed this to the actual issue and I'll leave it up to you if you want to close it

Interesting that HDR is only a problem in WebGL, or maybe for some reason default project settings put HDR in WebGL but not in Windows build

**Comment by ndumais** [comment]
Found a workaround where you `portalCamera.allowHdr = false;` while the main one keeps default settings
Issue is, in my case, that my HDR skybox wont render through the portal

**Comment by FredMarquer** [comment]
I think this is related to the RenderTexture used by the portalRenderCamera. In PortalRenderSystem.cs, around line 290, can you try to replace?
```
RenderTexture renderTexture = RenderTexture.GetTemporary(this.pixelWidth, this.pixelHeight, 32);
```
with
```
RenderTextureFormat format = PortalRenderSystem.portalRenderCamera.allowHDR ? RenderTextureFormat.DefaultHDR : RenderTextureFormat.Default;
RenderTexture renderTexture = RenderTexture.GetTemporary(this.pixelWidth, this.pixelHeight, 32, format);
```

**Comment by ndumais** [comment]
It was exactly that, I'm impressed, thanks again!
